version: "3.6"

networks:
  default:
    name: everest-demo-test
    enable_ipv6: true
    ipam:
      config:
        - subnet: 2001:db8:a::/64
          gateway: 2001:db8:a::1

services:
  mqtt-server:
    image: ghcr.io/everest/everest-demo/mqtt-server:${TAG}
    logging:
      driver: none

  manager:
    image: ghcr.io/everest/everest-demo/manager:${TAG}
    depends_on:
      - mqtt-server
    environment:
      - MQTT_SERVER_ADDRESS=mqtt-server
    working_dir: /ext/source/tests
    entrypoint: "sh ./run-test.sh; echo 'Ignoring result since tests are known to fail'"
    sysctls:
      - net.ipv6.conf.all.disable_ipv6=0
